; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Fire and Ice"
#define MyAppVersion "0.0.2"
#define MyAppPublisher "RRRobust Software"
#define MyAppExeName "FireAndIce.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DB59FCC4-0267-45C1-B96D-1C968E2B5A3F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=C:\Users\Kaleeb\Documents\GitHub\Capstone\Docs\License.txt
InfoBeforeFile=C:\Users\Kaleeb\Documents\GitHub\Capstone\README.md
InfoAfterFile=C:\Users\Kaleeb\Documents\GitHub\Capstone\README.md
OutputDir=C:\Users\Kaleeb\Documents\GitHub\Capstone\Deployable
OutputBaseFilename=Setup-FireAndIce-version_0.0.2a
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\FireAndIce.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\Content\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\Videos\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\Caliburn.Micro.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\Creeper.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\CreeperAI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\CreeperCore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\CreeperNetwork.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\Nine.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\Nine.Graphics.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\Nine.Physics.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\System.Windows.Interactivity.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\XNAControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Kaleeb\Documents\GitHub\Capstone\Fire and Ice\FireAndIce\bin\Release\XNAControlGame.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

